#!/usr/bin/env node

import path from 'path';
import fs from 'fs';
import open from 'open';
import { scanDirectory } from './scanner/index';
import { detectStack } from './scanner/detector';
import { analyzeArchitecture } from './analyzer/architecture';
import { analyzeDependencies } from './analyzer/dependencies';
import { analyzeModules } from './analyzer/modules';
import { analyzeConventions } from './analyzer/conventions';
import { startServer } from './server/index';
import { startMCPServer } from './mcp/server';
import { AnalysisResult } from './types';
import { detectProvider } from './ai/detector';

const VERSION = '1.0.0';

const RECENTS_PATH = path.join(
  process.env.HOME || process.env.USERPROFILE || '~',
  '.stackbrief',
  'recents.json'
);

function saveRecent(dirPath: string): void {
  try {
    const dir = path.dirname(RECENTS_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    let recents: Array<{ name: string; path: string }> = [];
    if (fs.existsSync(RECENTS_PATH)) {
      recents = JSON.parse(fs.readFileSync(RECENTS_PATH, 'utf-8'));
    }
    const entry = { name: path.basename(dirPath), path: dirPath };
    recents = recents.filter(r => r.path !== dirPath);
    recents.unshift(entry);
    fs.writeFileSync(RECENTS_PATH, JSON.stringify(recents.slice(0, 5), null, 2));
  } catch { /* non-fatal */ }
}

function printBanner() {
  console.log('');
  console.log('  stackbrief v' + VERSION);
  console.log('  Visual codebase intelligence');
  console.log('');
}

function printStep(step: string) {
  process.stdout.write(`  → ${step}\n`);
}

/**
 * Generates a structured CLAUDE.md file from the analysis result.
 * This file is written to the scanned project's root directory
 * so Claude Code and Cursor can use it as persistent project context.
 *
 * @param analysis - The complete analysis of the scanned codebase
 * @returns Formatted Markdown string ready to write to CLAUDE.md
 */
function generateClaudeMd(analysis: AnalysisResult): string {
  const { architecture, dependencies, conventions, modules, stack, repoName } = analysis;

  const lines: string[] = [
    `# ${repoName}`,
    ``,
    `> Generated by stackbrief — codebase intelligence for AI coding tools`,
    ``,
    `## Stack`,
    ``,
    `| | |`,
    `|---|---|`,
    `| Language | ${stack.language} |`,
    `| Runtime | ${stack.runtime} |`,
    `| Framework | ${stack.framework || '—'} |`,
    `| Package Manager | ${stack.packageManager} |`,
    stack.testFramework ? `| Test Framework | ${stack.testFramework} |` : '',
    stack.linter ? `| Linter | ${stack.linter} |` : '',
    stack.bundler ? `| Bundler | ${stack.bundler} |` : '',
    ``,
    `## Architecture`,
    ``,
    `**Pattern:** ${architecture.pattern}`,
    ``,
    architecture.database ? `**Database:** ${architecture.database}` : '',
    architecture.orm ? `**ORM:** ${architecture.orm}` : '',
    architecture.auth ? `**Auth:** ${architecture.auth}` : '',
    architecture.cache ? `**Cache:** ${architecture.cache}` : '',
    architecture.deployment ? `**Deployment:** ${architecture.deployment}` : '',
    architecture.hasDocker ? `**Docker:** Yes` : '',
    architecture.hasCI ? `**CI/CD:** Yes` : '',
    ``,
    `## Conventions`,
    ``,
    `| Convention | Style |`,
    `|---|---|`,
    `| Naming | ${conventions.namingStyle} |`,
    `| Async | ${conventions.asyncPattern} |`,
    `| Errors | ${conventions.errorHandling} |`,
    `| Modules | ${conventions.moduleSystem} |`,
    `| Validation | ${conventions.validation} |`,
    `| File layout | ${conventions.fileOrganization} |`,
    ``,
    `## Modules`,
    ``,
    ...modules.modules.slice(0, 12).map(m => `- \`${m.path}\` — ${m.description} (${m.fileCount} files)`),
    ``,
    `## Key Dependencies`,
    ``,
    ...dependencies.dependencies
      .filter(d => d.type === 'prod')
      .slice(0, 15)
      .map(d => `- \`${d.name}@${d.version}\` — ${d.description}`),
    ``,
    `---`,
    ``,
    `*Re-generate with \`npx stackbrief scan\`*`,
  ].filter(l => l !== '');

  return lines.join('\n') + '\n';
}

/**
 * Main scan pipeline: scans the target directory, runs all analyzers,
 * writes CLAUDE.md, starts the Express dashboard and MCP servers,
 * then opens the browser.
 *
 * @param targetDir - Absolute path to the directory to scan
 */
async function runScan(targetDir: string) {
  printBanner();

  const repoName = path.basename(targetDir);
  printStep(`Scanning ${repoName}`);

  const scan = scanDirectory(targetDir);
  printStep(`Found ${scan.totalFiles} files`);

  printStep('Detecting stack');
  const stack = detectStack(scan);

  printStep('Analyzing architecture');
  const architecture = analyzeArchitecture(scan, stack);

  printStep('Analyzing dependencies');
  const dependencies = analyzeDependencies(scan, stack.packageManager);

  printStep('Analyzing modules');
  const modules = analyzeModules(scan);

  printStep('Analyzing conventions');
  const conventions = analyzeConventions(scan);

  const analysis: AnalysisResult = {
    repoName,
    rootDir: targetDir,
    scannedAt: new Date().toISOString(),
    totalFiles: scan.totalFiles,
    stack,
    architecture,
    dependencies,
    modules,
    conventions
  };

  saveRecent(targetDir);
  printStep('Writing CLAUDE.md');
  // Always write CLAUDE.md to the directory being scanned, never to the
  // package's own directory. targetDir is either the explicit argument or
  // process.cwd() from where the user ran the command.
  const claudeMdPath = path.join(targetDir, 'CLAUDE.md');
  const claudeMdContent = generateClaudeMd(analysis);
  fs.writeFileSync(claudeMdPath, claudeMdContent, 'utf-8');

  printStep('Starting MCP server on port 3001');
  await startMCPServer(analysis, 3001);

  printStep('Starting dashboard server');
  const port = await startServer(analysis, 3000);

  // Detect AI provider (non-blocking)
  const aiInfo = await detectProvider();

  console.log('');
  console.log(`  Dashboard open at http://localhost:${port}`);
  console.log(`  MCP server at http://localhost:3001`);
  console.log(`  CLAUDE.md written to ${claudeMdPath}`);

  // AI status line
  if (aiInfo.available && aiInfo.provider && aiInfo.model) {
    const labels: Record<string, string> = { claude: 'Claude', openai: 'OpenAI', ollama: 'Ollama' };
    const providerLabel = labels[aiInfo.provider] || aiInfo.provider;
    const privacy = aiInfo.provider === 'ollama' ? ' - local, private' : ' - ready';
    console.log(`  AI Chat: ${providerLabel} (${aiInfo.model})${privacy}`);
  } else {
    console.log('  AI Chat: No provider configured');
    console.log('    Run with Ollama (free): ollama pull llama3');
    console.log('    Or set ANTHROPIC_API_KEY or OPENAI_API_KEY');
  }
  console.log('');

  // Open browser after 1s to ensure server is fully ready
  setTimeout(async () => {
    console.log('  Opening dashboard in browser...');
    try {
      await open(`http://localhost:${port}`);
    } catch {
      // Non-fatal if open fails (headless env, etc.)
    }
  }, 1000);

  console.log('  Press Ctrl+C to stop\n');
}

const args = process.argv.slice(2);
const command = args[0];

if (command === 'scan') {
  const targetDir = args[1] ? path.resolve(args[1]) : process.cwd();

  if (!fs.existsSync(targetDir)) {
    console.error(`  Error: Directory not found: ${targetDir}`);
    process.exit(1);
  }

  runScan(targetDir).catch(err => {
    console.error('  Error:', err.message);
    process.exit(1);
  });
} else if (command === '--version' || command === '-v') {
  console.log(VERSION);
} else if (!command || command === '--help' || command === '-h') {
  printBanner();
  console.log('  Usage:');
  console.log('    npx stackbrief scan           Scan current directory');
  console.log('    npx stackbrief scan <path>    Scan specific directory');
  console.log('');
} else {
  console.error(`  Unknown command: ${command}`);
  console.error('  Run "stackbrief --help" for usage');
  process.exit(1);
}
